// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Incident_State int32

const (
	Incident_UNRESOLVED Incident_State = 0
	Incident_RESOLVED   Incident_State = 1
	Incident_MONITORING Incident_State = 2
	Incident_IDLE       Incident_State = 3
)

// Enum value maps for Incident_State.
var (
	Incident_State_name = map[int32]string{
		0: "UNRESOLVED",
		1: "RESOLVED",
		2: "MONITORING",
		3: "IDLE",
	}
	Incident_State_value = map[string]int32{
		"UNRESOLVED": 0,
		"RESOLVED":   1,
		"MONITORING": 2,
		"IDLE":       3,
	}
)

func (x Incident_State) Enum() *Incident_State {
	p := new(Incident_State)
	*p = x
	return p
}

func (x Incident_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Incident_State) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (Incident_State) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x Incident_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Incident_State.Descriptor instead.
func (Incident_State) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0, 0}
}

type Incident_ComponentState int32

const (
	Incident_OPERATIONAL          Incident_ComponentState = 0
	Incident_UNDER_MAINTENANCE    Incident_ComponentState = 1
	Incident_DEGRADED_PERFORMANCE Incident_ComponentState = 2
	Incident_PARTIAL_OUTAGE       Incident_ComponentState = 3
	Incident_MAJOR_OUTAGE         Incident_ComponentState = 4
)

// Enum value maps for Incident_ComponentState.
var (
	Incident_ComponentState_name = map[int32]string{
		0: "OPERATIONAL",
		1: "UNDER_MAINTENANCE",
		2: "DEGRADED_PERFORMANCE",
		3: "PARTIAL_OUTAGE",
		4: "MAJOR_OUTAGE",
	}
	Incident_ComponentState_value = map[string]int32{
		"OPERATIONAL":          0,
		"UNDER_MAINTENANCE":    1,
		"DEGRADED_PERFORMANCE": 2,
		"PARTIAL_OUTAGE":       3,
		"MAJOR_OUTAGE":         4,
	}
)

func (x Incident_ComponentState) Enum() *Incident_ComponentState {
	p := new(Incident_ComponentState)
	*p = x
	return p
}

func (x Incident_ComponentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Incident_ComponentState) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (Incident_ComponentState) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x Incident_ComponentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Incident_ComponentState.Descriptor instead.
func (Incident_ComponentState) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0, 1}
}

type MetadataField_InputType int32

const (
	MetadataField_TEXT     MetadataField_InputType = 0
	MetadataField_PASSWORD MetadataField_InputType = 1
	MetadataField_CHECKBOX MetadataField_InputType = 2
	MetadataField_RADIO    MetadataField_InputType = 3
	MetadataField_SELECT   MetadataField_InputType = 4
)

// Enum value maps for MetadataField_InputType.
var (
	MetadataField_InputType_name = map[int32]string{
		0: "TEXT",
		1: "PASSWORD",
		2: "CHECKBOX",
		3: "RADIO",
		4: "SELECT",
	}
	MetadataField_InputType_value = map[string]int32{
		"TEXT":     0,
		"PASSWORD": 1,
		"CHECKBOX": 2,
		"RADIO":    3,
		"SELECT":   4,
	}
)

func (x MetadataField_InputType) Enum() *MetadataField_InputType {
	p := new(MetadataField_InputType)
	*p = x
	return p
}

func (x MetadataField_InputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataField_InputType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (MetadataField_InputType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x MetadataField_InputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataField_InputType.Descriptor instead.
func (MetadataField_InputType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6, 0}
}

type Incident struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Guid           string                  `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	CreatedAt      *LocalizedTime          `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *LocalizedTime          `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	State          Incident_State          `protobuf:"varint,4,opt,name=state,proto3,enum=types.Incident_State" json:"state,omitempty"`
	ComponentState Incident_ComponentState `protobuf:"varint,5,opt,name=component_state,json=componentState,proto3,enum=types.Incident_ComponentState" json:"component_state,omitempty"`
	Components     []*Component            `protobuf:"bytes,6,rep,name=components,proto3" json:"components,omitempty"`
	Messages       []*Message              `protobuf:"bytes,7,rep,name=messages,proto3" json:"messages,omitempty"`
	Metadata       []*MetadataEntry        `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty"`
	IsScheduled    bool                    `protobuf:"varint,9,opt,name=is_scheduled,json=isScheduled,proto3" json:"is_scheduled,omitempty"`
	ScheduledEnd   *LocalizedTime          `protobuf:"bytes,10,opt,name=scheduled_end,json=scheduledEnd,proto3" json:"scheduled_end,omitempty"`
	Origin         string                  `protobuf:"bytes,11,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *Incident) GetCreatedAt() *LocalizedTime {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Incident) GetUpdatedAt() *LocalizedTime {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Incident) GetState() Incident_State {
	if x != nil {
		return x.State
	}
	return Incident_UNRESOLVED
}

func (x *Incident) GetComponentState() Incident_ComponentState {
	if x != nil {
		return x.ComponentState
	}
	return Incident_OPERATIONAL
}

func (x *Incident) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Incident) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Incident) GetMetadata() []*MetadataEntry {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Incident) GetIsScheduled() bool {
	if x != nil {
		return x.IsScheduled
	}
	return false
}

func (x *Incident) GetScheduledEnd() *LocalizedTime {
	if x != nil {
		return x.ScheduledEnd
	}
	return nil
}

func (x *Incident) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsDisplayed   bool                   `protobuf:"varint,3,opt,name=is_displayed,json=isDisplayed,proto3" json:"is_displayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MetadataEntry) GetIsDisplayed() bool {
	if x != nil {
		return x.IsDisplayed
	}
	return false
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	CreatedAt     *LocalizedTime         `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *Message) GetCreatedAt() *LocalizedTime {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type LocalizedTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizedTime) Reset() {
	*x = LocalizedTime{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizedTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedTime) ProtoMessage() {}

func (x *LocalizedTime) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedTime.ProtoReflect.Descriptor instead.
func (*LocalizedTime) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *LocalizedTime) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LocalizedTime) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type RadioOpts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opts          []string               `protobuf:"bytes,4,rep,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadioOpts) Reset() {
	*x = RadioOpts{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadioOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioOpts) ProtoMessage() {}

func (x *RadioOpts) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioOpts.ProtoReflect.Descriptor instead.
func (*RadioOpts) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *RadioOpts) GetOpts() []string {
	if x != nil {
		return x.Opts
	}
	return nil
}

type MetadataField struct {
	state        protoimpl.MessageState  `protogen:"open.v1"`
	Name         string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id           string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Info         string                  `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	InputType    MetadataField_InputType `protobuf:"varint,4,opt,name=input_type,json=inputType,proto3,enum=types.MetadataField_InputType" json:"input_type,omitempty"`
	ForScheduled bool                    `protobuf:"varint,5,opt,name=for_scheduled,json=forScheduled,proto3" json:"for_scheduled,omitempty"`
	// Types that are valid to be assigned to Opts:
	//
	//	*MetadataField_RadioOpts
	//	*MetadataField_SelectOpts
	Opts isMetadataField_Opts `protobuf_oneof:"opts"`
	// Types that are valid to be assigned to DefaultOpt:
	//
	//	*MetadataField_DefaultOptKey
	DefaultOpt    isMetadataField_DefaultOpt `protobuf_oneof:"DefaultOpt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataField) Reset() {
	*x = MetadataField{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataField) ProtoMessage() {}

func (x *MetadataField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataField.ProtoReflect.Descriptor instead.
func (*MetadataField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *MetadataField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataField) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *MetadataField) GetInputType() MetadataField_InputType {
	if x != nil {
		return x.InputType
	}
	return MetadataField_TEXT
}

func (x *MetadataField) GetForScheduled() bool {
	if x != nil {
		return x.ForScheduled
	}
	return false
}

func (x *MetadataField) GetOpts() isMetadataField_Opts {
	if x != nil {
		return x.Opts
	}
	return nil
}

func (x *MetadataField) GetRadioOpts() *RadioOpts {
	if x != nil {
		if x, ok := x.Opts.(*MetadataField_RadioOpts); ok {
			return x.RadioOpts
		}
	}
	return nil
}

func (x *MetadataField) GetSelectOpts() *structpb.Struct {
	if x != nil {
		if x, ok := x.Opts.(*MetadataField_SelectOpts); ok {
			return x.SelectOpts
		}
	}
	return nil
}

func (x *MetadataField) GetDefaultOpt() isMetadataField_DefaultOpt {
	if x != nil {
		return x.DefaultOpt
	}
	return nil
}

func (x *MetadataField) GetDefaultOptKey() string {
	if x != nil {
		if x, ok := x.DefaultOpt.(*MetadataField_DefaultOptKey); ok {
			return x.DefaultOptKey
		}
	}
	return ""
}

type isMetadataField_Opts interface {
	isMetadataField_Opts()
}

type MetadataField_RadioOpts struct {
	RadioOpts *RadioOpts `protobuf:"bytes,6,opt,name=radio_opts,json=radioOpts,proto3,oneof"`
}

type MetadataField_SelectOpts struct {
	SelectOpts *structpb.Struct `protobuf:"bytes,7,opt,name=select_opts,json=selectOpts,proto3,oneof"`
}

func (*MetadataField_RadioOpts) isMetadataField_Opts() {}

func (*MetadataField_SelectOpts) isMetadataField_Opts() {}

type isMetadataField_DefaultOpt interface {
	isMetadataField_DefaultOpt()
}

type MetadataField_DefaultOptKey struct {
	DefaultOptKey string `protobuf:"bytes,8,opt,name=default_opt_key,json=defaultOptKey,proto3,oneof"`
}

func (*MetadataField_DefaultOptKey) isMetadataField_DefaultOpt() {}

type BaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Support       string                 `protobuf:"bytes,2,opt,name=support,proto3" json:"support,omitempty"`
	Contact       string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	TimeZone      string                 `protobuf:"bytes,5,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *BaseInfo) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *BaseInfo) GetSupport() string {
	if x != nil {
		return x.Support
	}
	return ""
}

func (x *BaseInfo) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *BaseInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BaseInfo) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseInfo      *BaseInfo              `protobuf:"bytes,1,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *InitRequest) GetBaseInfo() *BaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *InitRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type ListMetadataField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*MetadataField       `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetadataField) Reset() {
	*x = ListMetadataField{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetadataField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadataField) ProtoMessage() {}

func (x *ListMetadataField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadataField.ProtoReflect.Descriptor instead.
func (*ListMetadataField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ListMetadataField) GetFields() []*MetadataField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      *Incident              `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	TriggerByUser bool                   `protobuf:"varint,2,opt,name=trigger_by_user,json=triggerByUser,proto3" json:"trigger_by_user,omitempty"`
	Subscribers   []string               `protobuf:"bytes,3,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyRequest) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

func (x *NotifyRequest) GetTriggerByUser() bool {
	if x != nil {
		return x.TriggerByUser
	}
	return false
}

func (x *NotifyRequest) GetSubscribers() []string {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Incident as possibly mutated by the notifier, echoed back so the caller can persist changes
	Incident      *Incident `protobuf:"bytes,2,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ErrorResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescriptionResponse) Reset() {
	*x = DescriptionResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptionResponse) ProtoMessage() {}

func (x *DescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptionResponse.ProtoReflect.Descriptor instead.
func (*DescriptionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *DescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type IdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdResponse) Reset() {
	*x = IdResponse{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdResponse) ProtoMessage() {}

func (x *IdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdResponse.ProtoReflect.Descriptor instead.
func (*IdResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *IdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x05types\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x05\n" +
	"\bIncident\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x123\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x14.types.LocalizedTimeR\tcreatedAt\x123\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x14.types.LocalizedTimeR\tupdatedAt\x12+\n" +
	"\x05state\x18\x04 \x01(\x0e2\x15.types.Incident.StateR\x05state\x12G\n" +
	"\x0fcomponent_state\x18\x05 \x01(\x0e2\x1e.types.Incident.ComponentStateR\x0ecomponentState\x120\n" +
	"\n" +
	"components\x18\x06 \x03(\v2\x10.types.ComponentR\n" +
	"components\x12*\n" +
	"\bmessages\x18\a \x03(\v2\x0e.types.MessageR\bmessages\x120\n" +
	"\bmetadata\x18\b \x03(\v2\x14.types.MetadataEntryR\bmetadata\x12!\n" +
	"\fis_scheduled\x18\t \x01(\bR\visScheduled\x129\n" +
	"\rscheduled_end\x18\n" +
	" \x01(\v2\x14.types.LocalizedTimeR\fscheduledEnd\x12\x16\n" +
	"\x06origin\x18\v \x01(\tR\x06origin\"?\n" +
	"\x05State\x12\x0e\n" +
	"\n" +
	"UNRESOLVED\x10\x00\x12\f\n" +
	"\bRESOLVED\x10\x01\x12\x0e\n" +
	"\n" +
	"MONITORING\x10\x02\x12\b\n" +
	"\x04IDLE\x10\x03\"x\n" +
	"\x0eComponentState\x12\x0f\n" +
	"\vOPERATIONAL\x10\x00\x12\x15\n" +
	"\x11UNDER_MAINTENANCE\x10\x01\x12\x18\n" +
	"\x14DEGRADED_PERFORMANCE\x10\x02\x12\x12\n" +
	"\x0ePARTIAL_OUTAGE\x10\x03\x12\x10\n" +
	"\fMAJOR_OUTAGE\x10\x04\"Z\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12!\n" +
	"\fis_displayed\x18\x03 \x01(\bR\visDisplayed\"\x82\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x123\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x14.types.LocalizedTimeR\tcreatedAt\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"5\n" +
	"\tComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"[\n" +
	"\rLocalizedTime\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\x1f\n" +
	"\tRadioOpts\x12\x12\n" +
	"\x04opts\x18\x04 \x03(\tR\x04opts\"\xa4\x03\n" +
	"\rMetadataField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12=\n" +
	"\n" +
	"input_type\x18\x04 \x01(\x0e2\x1e.types.MetadataField.InputTypeR\tinputType\x12#\n" +
	"\rfor_scheduled\x18\x05 \x01(\bR\fforScheduled\x121\n" +
	"\n" +
	"radio_opts\x18\x06 \x01(\v2\x10.types.RadioOptsH\x00R\tradioOpts\x12:\n" +
	"\vselect_opts\x18\a \x01(\v2\x17.google.protobuf.StructH\x00R\n" +
	"selectOpts\x12(\n" +
	"\x0fdefault_opt_key\x18\b \x01(\tH\x01R\rdefaultOptKey\"H\n" +
	"\tInputType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\f\n" +
	"\bPASSWORD\x10\x01\x12\f\n" +
	"\bCHECKBOX\x10\x02\x12\t\n" +
	"\x05RADIO\x10\x03\x12\n" +
	"\n" +
	"\x06SELECT\x10\x04B\x06\n" +
	"\x04optsB\f\n" +
	"\n" +
	"DefaultOpt\"\x8c\x01\n" +
	"\bBaseInfo\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x18\n" +
	"\asupport\x18\x02 \x01(\tR\asupport\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1b\n" +
	"\ttime_zone\x18\x05 \x01(\tR\btimeZone\"l\n" +
	"\vInitRequest\x12,\n" +
	"\tbase_info\x18\x01 \x01(\v2\x0f.types.BaseInfoR\bbaseInfo\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\"A\n" +
	"\x11ListMetadataField\x12,\n" +
	"\x06fields\x18\x01 \x03(\v2\x14.types.MetadataFieldR\x06fields\"\x1f\n" +
	"\x05Error\x12\x16\n" +
	"\x06detail\x18\x01 \x01(\tR\x06detail\"\x86\x01\n" +
	"\rNotifyRequest\x12+\n" +
	"\bincident\x18\x01 \x01(\v2\x0f.types.IncidentR\bincident\x12&\n" +
	"\x0ftrigger_by_user\x18\x02 \x01(\bR\rtriggerByUser\x12 \n" +
	"\vsubscribers\x18\x03 \x03(\tR\vsubscribers\"`\n" +
	"\rErrorResponse\x12\"\n" +
	"\x05error\x18\x01 \x01(\v2\f.types.ErrorR\x05error\x12+\n" +
	"\bincident\x18\x02 \x01(\v2\x0f.types.IncidentR\bincident\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x13DescriptionResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"\x1c\n" +
	"\n" +
	"IdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x99\x03\n" +
	"\bNotifier\x122\n" +
	"\x04Init\x12\x12.types.InitRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\x04Name\x12\x16.google.protobuf.Empty\x1a\x13.types.NameResponse\x12A\n" +
	"\vDescription\x12\x16.google.protobuf.Empty\x1a\x1a.types.DescriptionResponse\x12/\n" +
	"\x02Id\x12\x16.google.protobuf.Empty\x1a\x11.types.IdResponse\x124\n" +
	"\x06Notify\x12\x14.types.NotifyRequest\x1a\x14.types.ErrorResponse\x12B\n" +
	"\x0eMetadataFields\x12\x16.google.protobuf.Empty\x1a\x18.types.ListMetadataField\x126\n" +
	"\bPreCheck\x12\x14.types.NotifyRequest\x1a\x14.types.ErrorResponseBBZ@github.com/orange-cloudfoundry/statusetat/notifiers/plugin/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_plugin_proto_goTypes = []any{
	(Incident_State)(0),           // 0: types.Incident.State
	(Incident_ComponentState)(0),  // 1: types.Incident.ComponentState
	(MetadataField_InputType)(0),  // 2: types.MetadataField.InputType
	(*Incident)(nil),              // 3: types.Incident
	(*MetadataEntry)(nil),         // 4: types.MetadataEntry
	(*Message)(nil),               // 5: types.Message
	(*Component)(nil),             // 6: types.Component
	(*LocalizedTime)(nil),         // 7: types.LocalizedTime
	(*RadioOpts)(nil),             // 8: types.RadioOpts
	(*MetadataField)(nil),         // 9: types.MetadataField
	(*BaseInfo)(nil),              // 10: types.BaseInfo
	(*InitRequest)(nil),           // 11: types.InitRequest
	(*ListMetadataField)(nil),     // 12: types.ListMetadataField
	(*Error)(nil),                 // 13: types.Error
	(*NotifyRequest)(nil),         // 14: types.NotifyRequest
	(*ErrorResponse)(nil),         // 15: types.ErrorResponse
	(*NameResponse)(nil),          // 16: types.NameResponse
	(*DescriptionResponse)(nil),   // 17: types.DescriptionResponse
	(*IdResponse)(nil),            // 18: types.IdResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 20: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 21: google.protobuf.Empty
}
var file_plugin_proto_depIdxs = []int32{
	7,  // 0: types.Incident.created_at:type_name -> types.LocalizedTime
	7,  // 1: types.Incident.updated_at:type_name -> types.LocalizedTime
	0,  // 2: types.Incident.state:type_name -> types.Incident.State
	1,  // 3: types.Incident.component_state:type_name -> types.Incident.ComponentState
	6,  // 4: types.Incident.components:type_name -> types.Component
	5,  // 5: types.Incident.messages:type_name -> types.Message
	4,  // 6: types.Incident.metadata:type_name -> types.MetadataEntry
	7,  // 7: types.Incident.scheduled_end:type_name -> types.LocalizedTime
	7,  // 8: types.Message.created_at:type_name -> types.LocalizedTime
	19, // 9: types.LocalizedTime.time:type_name -> google.protobuf.Timestamp
	2,  // 10: types.MetadataField.input_type:type_name -> types.MetadataField.InputType
	8,  // 11: types.MetadataField.radio_opts:type_name -> types.RadioOpts
	20, // 12: types.MetadataField.select_opts:type_name -> google.protobuf.Struct
	10, // 13: types.InitRequest.base_info:type_name -> types.BaseInfo
	20, // 14: types.InitRequest.params:type_name -> google.protobuf.Struct
	9,  // 15: types.ListMetadataField.fields:type_name -> types.MetadataField
	3,  // 16: types.NotifyRequest.incident:type_name -> types.Incident
	13, // 17: types.ErrorResponse.error:type_name -> types.Error
	3,  // 18: types.ErrorResponse.incident:type_name -> types.Incident
	11, // 19: types.Notifier.Init:input_type -> types.InitRequest
	21, // 20: types.Notifier.Name:input_type -> google.protobuf.Empty
	21, // 21: types.Notifier.Description:input_type -> google.protobuf.Empty
	21, // 22: types.Notifier.Id:input_type -> google.protobuf.Empty
	14, // 23: types.Notifier.Notify:input_type -> types.NotifyRequest
	21, // 24: types.Notifier.MetadataFields:input_type -> google.protobuf.Empty
	14, // 25: types.Notifier.PreCheck:input_type -> types.NotifyRequest
	21, // 26: types.Notifier.Init:output_type -> google.protobuf.Empty
	16, // 27: types.Notifier.Name:output_type -> types.NameResponse
	17, // 28: types.Notifier.Description:output_type -> types.DescriptionResponse
	18, // 29: types.Notifier.Id:output_type -> types.IdResponse
	15, // 30: types.Notifier.Notify:output_type -> types.ErrorResponse
	12, // 31: types.Notifier.MetadataFields:output_type -> types.ListMetadataField
	15, // 32: types.Notifier.PreCheck:output_type -> types.ErrorResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[6].OneofWrappers = []any{
		(*MetadataField_RadioOpts)(nil),
		(*MetadataField_SelectOpts)(nil),
		(*MetadataField_DefaultOptKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
